"""Export one registry-resolved HIK adapter as a data-self-contained module."""

from __future__ import annotations

import base64
import hashlib
import json
import textwrap
from pathlib import Path
from typing import Dict, Mapping

from aria_trace.adapters.filesystem.profile_registry import (
    AdapterRequest,
    ProfileContext,
    ProfileRegistry,
)


def _literal(data: bytes) -> str:
    encoded = base64.b64encode(data).decode("ascii")
    chunks = textwrap.wrap(encoded, 96) or [""]
    return "(\n{}\n    )".format(
        "\n".join("        {!r}".format(chunk) for chunk in chunks)
    )


def _profile_document(path: Path) -> Dict[str, object]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def export_resolved_adapter(
    output: Path,
    *,
    registry: ProfileRegistry,
    context: ProfileContext,
    request: AdapterRequest,
) -> Mapping[str, object]:
    """Embed the exact resolved calibration/profile data into one Python file.

    The generated module still requires the AriaTrace Python camera package,
    NumPy/OpenCV, and the vendor MVS runtime.  It has no profile-registry or
    calibration-file dependency: all runtime calibration blobs are embedded
    and materialized into a content-addressed temporary cache on first use.
    """

    output = Path(output).resolve()
    resolved = registry.resolve_adapter(context, request)
    rig_path = Path(resolved["paths"]["rig_calibration"])
    rig_document = _profile_document(rig_path)
    blobs: Dict[str, bytes] = {}

    dense_name = str((rig_document.get("normalization") or {}).get("dense_map_file") or "")
    if dense_name:
        rig_profile = registry.revision(str(resolved["profiles"]["rig"]))
        dense_path = None
        try:
            dense_path = registry.runtime_file(rig_profile, "rectification_maps")
        except KeyError:
            candidate = rig_path.parent / dense_name
            if candidate.is_file():
                dense_path = candidate
        if dense_path is not None and Path(dense_path).is_file():
            embedded_dense_name = "rectification_maps{}".format(
                Path(dense_path).suffix.lower() or ".npz"
            )
            rig_document["normalization"]["dense_map_file"] = embedded_dense_name
            blobs[embedded_dense_name] = Path(dense_path).read_bytes()
        else:
            # Homography remains a complete supported normalization fallback.
            rig_document["normalization"]["dense_map_file"] = None
    blobs["hik_camera_calibration.json"] = json.dumps(
        rig_document, indent=2, sort_keys=True
    ).encode("utf-8")

    minimap_path = resolved["paths"].get("rig_game_profile")
    if minimap_path:
        blobs["rig_game_profile.json"] = Path(minimap_path).read_bytes()
    color_path = resolved["paths"].get("game_color_profile")
    if color_path and Path(color_path).resolve() != Path(minimap_path or "").resolve():
        blobs["game_color_profile.json"] = Path(color_path).read_bytes()
    elif color_path:
        # One legacy profile can own both mini-map geometry and color.
        blobs["game_color_profile.json"] = blobs["rig_game_profile.json"]

    digest = hashlib.sha256()
    for name in sorted(blobs):
        digest.update(name.encode("utf-8"))
        digest.update(blobs[name])
    content_id = digest.hexdigest()
    encoded_rows = ",\n".join(
        "    {!r}: {}".format(name, _literal(blobs[name]))
        for name in sorted(blobs)
    )
    defaults = {
        "mode": resolved["adapter_plan"]["mode"],
        "rectify": bool(resolved["adapter_plan"]["rectify"]),
        "color_order": resolved["adapter_plan"]["color_order"],
        "color_policy": resolved["adapter_plan"]["color_policy"],
        "minimap_margin_px": resolved["adapter_plan"]["minimap_margin_px"],
    }
    revisions = dict(resolved["profiles"])
    source = '''# Generated by AriaTrace. Calibration/profile data is embedded below.
# External requirements: aria_trace Python package, NumPy/OpenCV, and HIK MVS.
# Registry reads: none. Phone operations: none.

from __future__ import annotations

import base64
import os
import tempfile
from pathlib import Path

from aria_trace.adapters.hik.compat import HikCamera as _HikCamera
from aria_trace.adapters.hik.compat import MultiHikCamera

CONTENT_SHA256 = {content_id!r}
PROFILE_REVISIONS = {revisions!r}
DEFAULT_CONFIG = {defaults!r}
_BLOBS = {{
{encoded_rows}
}}
_PATHS = None


def _materialize():
    global _PATHS
    if _PATHS is not None:
        return _PATHS
    root = Path(tempfile.gettempdir()) / "aria-trace-embedded-adapters" / CONTENT_SHA256
    root.mkdir(parents=True, exist_ok=True)
    paths = {{}}
    for name, encoded in _BLOBS.items():
        path = root / name
        payload = base64.b64decode(encoded)
        if not path.is_file() or path.read_bytes() != payload:
            temporary = path.with_suffix(path.suffix + ".tmp-{{}}".format(os.getpid()))
            temporary.write_bytes(payload)
            os.replace(str(temporary), str(path))
        paths[name] = path
    _PATHS = paths
    return paths


class HikCamera(_HikCamera):
    """HIK-shaped adapter pinned to the embedded immutable calibration."""

    def __init__(self, ip=None, host_ip=None, setting_items=None, config=None):
        supplied = dict(config or {{}})
        forbidden = sorted(set(supplied).intersection((
            "profile_root", "game_id", "phone_id", "phone_serial",
            "panel_display", "game_display", "calibration",
            "diagnostic_calibration_override", "minimap_calibration",
            "game_color_calibration",
        )))
        if forbidden:
            raise ValueError(
                "Embedded adapter does not resolve external profiles: {{}}".format(
                    ", ".join(forbidden)
                )
            )
        paths = _materialize()
        effective = dict(DEFAULT_CONFIG)
        effective.update(supplied)
        effective["diagnostic_calibration_override"] = paths[
            "hik_camera_calibration.json"
        ]
        if "rig_game_profile.json" in paths:
            effective["minimap_calibration"] = paths["rig_game_profile.json"]
        elif effective.get("mode") in ("minimap", "dual"):
            raise ValueError("This embedded adapter contains rig calibration only")
        if "game_color_profile.json" in paths:
            effective["game_color_calibration"] = paths[
                "game_color_profile.json"
            ]
        elif effective.get("color_policy") == "game_matched":
            raise ValueError("This embedded adapter has no game-color calibration")
        super().__init__(
            ip=ip,
            host_ip=host_ip,
            setting_items=setting_items,
            config=effective,
        )


get_cam = HikCamera.get_cam
get_cams = HikCamera.get_cams
get_all_cams = HikCamera.get_all_cams
get_all_ips = HikCamera.get_all_ips

__all__ = [
    "HikCamera", "MultiHikCamera", "get_cam", "get_cams",
    "get_all_cams", "get_all_ips", "CONTENT_SHA256", "PROFILE_REVISIONS",
]
'''.format(
        content_id=content_id,
        revisions=revisions,
        defaults=defaults,
        encoded_rows=encoded_rows,
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text(source, encoding="utf-8")
    compile(source, str(output), "exec")
    temporary.replace(output)
    return {
        "schema_version": "1.0",
        "output": str(output),
        "content_sha256": content_id,
        "profile_revisions": revisions,
        "embedded_files": sorted(blobs),
        "defaults": defaults,
        "registry_reads_at_runtime": 0,
    }


__all__ = ["export_resolved_adapter"]
